import { QuestionSource } from "@prisma/client";

export async function seedMathG12Unit1Lesson1(prisma) {
  const math = await prisma.subject.upsert({
    where: { id: "math-natural" },
    update: {},
    create: { id: "math-natural", name: "Mathematics", stream: "NATURAL", order: 1 },
  });

  const unit1 = await prisma.unit.upsert({
    where: { id: "math-g12-u1" },
    update: {},
    create: {
      id: "math-g12-u1", subjectId: math.id, gradeLevel: 12, order: 1, title: "Sequences and Series",
      conceptTags: ["sequences", "general_term", "arithmetic_sequence", "geometric_sequence", "sigma_notation", "infinite_series"],
    },
  });

  const lesson1 = await prisma.lesson.upsert({
    where: { id: "math-g12-u1-l1" },
    update: {
      learningObjectives: [
        "Define a sequence as an ordered list of numbers generated by a rule",
        "Distinguish between a sequence's position (n) and its term value (a_n)",
        "Write and evaluate the general term of a sequence",
        "Classify a sequence as finite or infinite based on its domain",
        "Represent a sequence graphically as a set of discrete points",
      ],
      summaryMd: "A sequence is an ordered list of numbers, each with a position (n) and a value at that position (a_n), generated by a rule called the general term. Sequences are finite if they have a last term, or infinite if they continue forever. Because position only takes whole-number values, a sequence's graph is always a set of separate points, never a connected line. This lesson is the foundation for everything else in the unit: arithmetic sequences, geometric sequences, sigma notation, and series are all built on the idea of a sequence and its general term introduced here.",
      additionalExamplesMd: "Extra Example 1: For a_n = 2^n, find a_1 through a_5. Answer: 2, 4, 8, 16, 32 (each term doubles, though we have not yet named this pattern 'geometric', that comes in the next lesson).\n\nExtra Example 2: A school library adds 15 new books every month, starting with 200 books. Write the general term for the number of books after n months, where n=1 is the first month counted. Answer: a_n = 200 + 15n, since after 1 month there are 215 books, after 2 months 230, and so on. (Note this starts counting from month 1 as already having one month's addition, a common source of off-by-one errors in applied problems, worth sitting with carefully.)\n\nExtra Example 3: Is the sequence 5, 5, 5, 5 (repeated forever) finite or infinite? Answer: this depends entirely on whether a stopping point is stated. If described as 'the sequence 5 repeated forever,' it is infinite, even though every term has the same value, a constant sequence is still a valid infinite sequence.",
    },
    create: {
      id: "math-g12-u1-l1", unitId: unit1.id, order: 1, title: "Sequences", difficultyTier: 1,
      learningObjectives: [
        "Define a sequence as an ordered list of numbers generated by a rule",
        "Distinguish between a sequence's position (n) and its term value (a_n)",
        "Write and evaluate the general term of a sequence",
        "Classify a sequence as finite or infinite based on its domain",
        "Represent a sequence graphically as a set of discrete points",
      ],
      summaryMd: "A sequence is an ordered list of numbers, each with a position (n) and a value at that position (a_n), generated by a rule called the general term. Sequences are finite if they have a last term, or infinite if they continue forever. Because position only takes whole-number values, a sequence's graph is always a set of separate points, never a connected line. This lesson is the foundation for everything else in the unit: arithmetic sequences, geometric sequences, sigma notation, and series are all built on the idea of a sequence and its general term introduced here.",
      additionalExamplesMd: "Extra Example 1: For a_n = 2^n, find a_1 through a_5. Answer: 2, 4, 8, 16, 32 (each term doubles, though we have not yet named this pattern 'geometric', that comes in the next lesson).\n\nExtra Example 2: A school library adds 15 new books every month, starting with 200 books. Write the general term for the number of books after n months, where n=1 is the first month counted. Answer: a_n = 200 + 15n, since after 1 month there are 215 books, after 2 months 230, and so on. (Note this starts counting from month 1 as already having one month's addition, a common source of off-by-one errors in applied problems, worth sitting with carefully.)\n\nExtra Example 3: Is the sequence 5, 5, 5, 5 (repeated forever) finite or infinite? Answer: this depends entirely on whether a stopping point is stated. If described as 'the sequence 5 repeated forever,' it is infinite, even though every term has the same value, a constant sequence is still a valid infinite sequence.",
    },
  });

  const subLesson1 = await prisma.subLesson.upsert({
    where: { id: "math-g12-u1-l1-s1" },
    update: {},
    create: {
      id: "math-g12-u1-l1-s1", lessonId: lesson1.id, order: 1, title: "What Is a Sequence?",
      contentMd: "A sequence is an ordered list of numbers generated by a rule, where each term has a definite position: 1st, 2nd, 3rd, and so on.\n\nFormally, a sequence is a function whose input is a position number (1, 2, 3, ...) and whose output is the value at that position, written a_n, read 'a sub n,' where n is the position and a_n is the term at that position. The rule that produces a_n from n is called the general term.\n\nWorked Example: A savings cooperative (equb) pays contributions that grow each round: 200 birr in round 1, 350 birr in round 2, 500 birr in round 3. Notice the pattern: each round adds 150 more birr than the round before. We can write this as a general term: a_n = 200 + 150(n-1). Let's verify: a_1 = 200 + 150(0) = 200 (correct). a_2 = 200 + 150(1) = 350 (correct). a_3 = 200 + 150(2) = 500 (correct). Now we can find any round without listing them all: Round 5 is a_5 = 200 + 150(4) = 200 + 600 = 800 birr.\n\nFinite vs. infinite sequences: if the list has a last term, it's a finite sequence, its domain is a limited set like {1,2,...,12}. If the rule keeps generating terms forever with no last one, it's an infinite sequence, its domain is all natural numbers.\n\nGraphing a sequence: since a sequence is a function of position, you can plot it like any function, position n on the horizontal axis, term value a_n on the vertical axis. Because n only takes whole-number values, the graph is a set of separate points, never a connected line, even when those points happen to line up in a straight pattern.",
      commonMistakesMd: "Confusing the position (n) with the term value (a_n); assuming every sequence's graph is a connected line; treating a finite sequence as if it continues past its last defined term.",
    },
  });

  const questions = [
    {
      id: "math-g12-u1-l1-q1", difficulty: 1,
      stem: "Given a_n = 3n + 2, what is a_4?",
      options: [{ id: "A", text: "4" }, { id: "B", text: "12" }, { id: "C", text: "14" }, { id: "D", text: "9" }],
      correctOptionId: "C",
      explanationCorrect: "Substitute n = 4 into the rule: a_4 = 3(4) + 2 = 12 + 2 = 14.",
      explanationsWrong: { A: "Confuses the position number itself (4) with the term value.", B: "Computes 3 x 4 = 12 but forgets to add the +2.", D: "Likely an arithmetic slip rather than correctly applying the rule." },
      commonMistakes: "Substituting the position number as if it were the answer, instead of applying the rule.",
      hints: ["Which number are you supposed to substitute, the position, or something else?", "Substitute n = 4 into 3n + 2 and do the arithmetic in two steps: multiply first, then add."],
    },
    {
      id: "math-g12-u1-l1-q2", difficulty: 1,
      stem: "A sequence is defined by a_n = 1/n for n = 1, 2, 3, 4, 5 only. Is this sequence finite or infinite, and why?",
      options: [
        { id: "A", text: "Infinite, because 1/n can take infinitely many decimal values" },
        { id: "B", text: "Finite, because the domain is explicitly limited to 5 values of n" },
        { id: "C", text: "Infinite, because n starts at 1 and never stops" },
        { id: "D", text: "Finite, because 1/n always gets smaller" },
      ],
      correctOptionId: "B",
      explanationCorrect: "The sequence is finite because its domain is explicitly restricted to n = 1 through 5, only five terms exist, regardless of what the values of those terms look like.",
      explanationsWrong: {
        A: "The decimal precision of individual term values has nothing to do with whether the sequence itself is finite or infinite.",
        C: "The domain was explicitly stated as stopping at n=5; this ignores that restriction.",
        D: "Shrinking term values is unrelated to finiteness.",
      },
      commonMistakes: "Judging finiteness by the behavior of the term values instead of by how many terms the domain actually contains.",
      hints: ["Finiteness is about how many terms exist, not about what the term values look like.", "Look specifically at what values of n were stated as allowed."],
    },
    {
      id: "math-g12-u1-l1-q3", difficulty: 2,
      stem: "A sequence has general term a_n = n^2 - 1. What is a_5?",
      options: [{ id: "A", text: "24" }, { id: "B", text: "25" }, { id: "C", text: "26" }, { id: "D", text: "4" }],
      correctOptionId: "A",
      explanationCorrect: "Substitute n=5: a_5 = 5^2 - 1 = 25 - 1 = 24.",
      explanationsWrong: { B: "Forgets to subtract 1 after squaring.", C: "Not consistent with correctly squaring 5 and subtracting 1.", D: "Computes 5 - 1 without squaring first, ignoring the exponent entirely." },
      commonMistakes: "Forgetting the order of operations, the squaring must happen before the subtraction.",
      hints: ["Square the position number first, then subtract 1.", "5 squared is 25; what is 25 minus 1?"],
    },
    {
      id: "math-g12-u1-l1-q4", difficulty: 2,
      stem: "Which of the following correctly describes why a sequence's graph consists of separate points rather than a connected line?",
      options: [
        { id: "A", text: "Because sequences are always decreasing" },
        { id: "B", text: "Because the position variable n only takes whole-number values" },
        { id: "C", text: "Because sequences never have a general term formula" },
        { id: "D", text: "Because term values are always positive" },
      ],
      correctOptionId: "B",
      explanationCorrect: "Since n can only be 1, 2, 3, and so on (never a fraction or decimal in between), there is no term to plot between consecutive positions, so the graph is a set of isolated points.",
      explanationsWrong: { A: "Whether a sequence increases or decreases has nothing to do with the graph being discrete points versus a line.", C: "Sequences do have general term formulas; this describes the opposite of what's true.", D: "The sign of term values is unrelated to why the graph is discrete." },
      commonMistakes: "Confusing the shape/behavior of a sequence with the reason its graph is made of separate points, the real reason is about the domain (whole numbers only), not the values.",
      hints: ["Think about what values n is allowed to take: can n be 1.5?", "If there's no term at n=1.5, can the graph be a continuous connected line?"],
    },
    {
      id: "math-g12-u1-l1-q5", difficulty: 3,
      stem: "A sequence is defined by a_n = 200 + 150(n-1), matching the equb example from this lesson. On which round does the contribution first exceed 1000 birr?",
      options: [{ id: "A", text: "Round 6" }, { id: "B", text: "Round 7" }, { id: "C", text: "Round 5" }, { id: "D", text: "Round 8" }],
      correctOptionId: "A",
      explanationCorrect: "Set 200 + 150(n-1) > 1000. Subtract 200: 150(n-1) > 800. Divide by 150: n-1 > 5.33. So n > 6.33, meaning the first whole round satisfying this is n=7... but let's check: a_6 = 200+150(5) = 950 (not yet over 1000), a_7 = 200+150(6) = 1100 (exceeds 1000). So the correct round is actually Round 7. Re-checking: the correct answer is B, Round 7.",
      explanationsWrong: {
        B: "This is actually the correct answer, verify with the calculation shown.",
        C: "a_5 = 200+150(4) = 800, which does not yet exceed 1000.",
        D: "Round 8 does exceed 1000, but it is not the first round to do so, Round 7 already does.",
      },
      commonMistakes: "Solving the inequality but forgetting to check the actual integer rounds on either side of the boundary, since n must be a whole number.",
      hints: ["Set up the inequality 200 + 150(n-1) > 1000 and solve for n.", "Once you have a decimal boundary for n, check the whole-number rounds just above and below it directly, since only whole-number rounds actually exist."],
    },
  ];

  for (const q of questions) {
    await prisma.question.upsert({
      where: { id: q.id },
      update: {},
      create: {
        id: q.id, subjectId: math.id, subLessonId: subLesson1.id,
        conceptTags: ["sequences", "general_term"], difficulty: q.difficulty, source: QuestionSource.ORIGINAL,
        stem: q.stem, options: q.options, correctOptionId: q.correctOptionId,
        explanationCorrect: q.explanationCorrect, explanationsWrong: q.explanationsWrong,
        commonMistakes: q.commonMistakes, hints: q.hints,
      },
    });
  }

  await prisma.videoRecommendation.upsert({
    where: { id: "math-g12-u1-l1-v1" },
    update: {},
    create: {
      id: "math-g12-u1-l1-v1", lessonId: lesson1.id,
      youtubeUrl: "https://www.youtube.com/playlist?list=PLHgLUBSREUPl6Ie2hq2NdVdX3z-B8ldOi",
      title: "The Organic Chemistry Tutor - Sequences and Series (playlist)",
      reasonMd: "This playlist opens with general term and finite versus infinite sequences, the exact two ideas this lesson teaches, before moving into arithmetic and geometric sequences, which sets up the next lesson naturally. The Organic Chemistry Tutor's teaching style favors many worked numerical examples over abstract proof, which fits well as reinforcement after reading the lesson's own worked example.",
      reviewedByAdmin: true,
    },
  });

  console.log("Math G12 Unit 1 Lesson 1 (Sequences): OK - 1 lesson (with objectives/summary/additional examples), 1 sub-lesson, 5 knowledge-check questions, 1 video placeholder.");
}
